baseURL = "https://eugenelerman.net/"
languageCode = "en-us"
title = "Eugene Lerman"
theme="archie"
copyright = "© Eugen Lerman"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
googleAnalytics = "UA-166079199-1"
paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark or auto
	featherIconsCDN=true
	# subtitle = "Shalom"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/airbugg/eugenelerman.net"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/airbagy"

[[params.social]]
name = "Facebbok"
icon = "facebook"
url = "https://www.facebook.com/airbug"

# Main menu Items

[[menu.main]]
name = "/"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "CV"
url = "/curriculum-vitae.pdf"
weight = 3

[[menu.main]]
name = "Watchlist"
url = "/posts/hard"
weight = 4

[[menu.main]]
name = "About"
url = "/about"
weight = 5