baseURL = "https://eugenelerman.net/"
languageCode = "en-us"
title = "Eugene Lerman"
theme="archie"
copyright = "© Eugene Lerman"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
googleAnalytics = "UA-166079199-1"
paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark or auto
	featherIconsCDN=true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/airbugg"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/airbagy"

[[params.social]]
name = "Facebbok"
icon = "facebook"
url = "https://www.facebook.com/airbug"

# Menu Items

[[menu.main]]
name = "/"
url = "/"
weight = 1

[[menu.main]]
name = "/posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "/watchlist"
url = "/posts/watch"
weight = 3

[[menu.main]]
name = "/reading list"
url = "/posts/read"
weight = 4

[[menu.main]]
name = "/cv"
url = "/curriculum-vitae.pdf"
weight = 5