baseURL = "https://eugenelerman.net/"
languageCode = "en-us"
title = "Eugene Lerman"
theme="archie"
copyright = "© Eugene Lerman"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
googleAnalytics = "UA-166079199-1"
# paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark or auto
	featherIconsCDN=true
  # titleCutting = true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/airbugg"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/airbagy"

[[params.social]]
name = "Facebbok"
icon = "facebook"
url = "https://www.facebook.com/airbug"

# archie menu items
# [[menu.main]]
# name = "/"
# url = "/"
# weight = 1

[[menu.main]]
name = "/posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "/recommended videos"
url = "/watchlist"
weight = 3

[[menu.main]]
name = "/recommended reading"
url = "/recommended-reading"
weight = 4

# hugo-theme-console menu items
[[params.navlinks]]
name = "posts/"
url = "posts/"

[[params.navlinks]]
name = "recommended videos/"
url = "/posts/watch"

[[params.navlinks]]
name = "recommended reading/"
url = "/posts/reading"

[[params.navlinks]]
name = "cv/"
url = "/curriculum-vitae.pdf"
